#Descrições das expressões

alimentos_caros = ['alimentos_caros','Aquisição de alimentos caros.']
bebidas_alcoolicas = ['bebidas_alcoolicas', 'Aquisição de bebidas alcoólicas.']
comida_japonesa = ['comida_japonesa','Aquisição de alimentos caros.']
itens_caros = ['itens_caros','Aquisição de itens caros.']
certidao_protesto = ['certidao_protesto','Exigência de certidão negativa de protesto para habilitação.']
certidao_corregedor = ['certidao_corregedor','Exigência de certidão negativa de corregedoria de justiça para habilitação.']
integralizado = ['integralizado','Exigência de comprovação de capital social ou patrimônio lí­quido integralizados para habilitação.']
garantia_cs_ou_pl = ['garantia_cs_ou_pl','Exigência cumulativa de garantia de proposta, capital social mínimo ou patrimônio líquido mínimo para habilitação.'] 
idoneidade_financeira = ['idoneidade_financeira','Exigência de idoneidade financeira ou bancária para habilitação.']
vedacao_impugnacao = ['vedacao_impugnacao','Vedação de impugnação não presencial no processo licitatório.']
certidao_quitacao = ['certidao_quitacao','Exigência de certidão negativa de quitação para habilitação.']
carta_credenciamento = ['carta_credenciamento','Exigência de carta de credenciamento emitida pelo fabricante para habilitação.']
quadro_permanente = ['quadro_permanente','Exigência de comprovação de quadro permanente sem permitir contrato de prestação de serviços para habilitação.']
filiacao_abav_iata = ['filiacao_abav_iata','Exigência de filiação ABAV e IATA nas licitações de passagens aéreas para habilitação.']
visto_registro_profissional = ['visto_registro_profissional','Exigência para licitante de outro estado de visto do registro profissional para habilitação.']
comprovante_localizacao = ['comprovante_localizacao','Exigência de alvará de funcionamento ou outra comprovação de localização do licitante para habilitação.']
usina_asfalto_cbuq = ['usina_asfalto_cbuq','Exigência de comprovação de disponibilidade ou propriedade de usina de asfalto para habilitação.']
amostra_prototipo = ['amostra_prototipo','Exigência de amostra ou protótipo de todos os licitantes na fase de habilitação.']
n_min_max_limitacao_atestados = ['n_min_max_limitacao_atestados','Exigência de número mínimo, máximo ou limitação de somatório de atestados de capacidade técnica para habilitação.']
preferencia_prod_nacionais = ['preferencia_prod_nacionais','A margem de preferência citada no § 12 do art. 3º da Lei 8.666/93 deve ter regulamentação por decreto.']
temp_exp_profissional = ['temp_exp_profissional','Exigência de tempo de experiência profissional para habilitação.']
atestado_compactador = ['atestado_compactador','Exigência de comprovação da capacidade técnico-operacional das licitantes para serviços comuns em obras.']
atestado_aterro = ['atestado_aterro','Exigência de comprovação da capacidade técnico-operacional das licitantes para serviços comuns em obras.']
atestado_demolicao = ['atestado_demolicao','Exigência de comprovação da capacidade técnico-operacional das licitantes para serviços comuns em obras.']
atestado_lastro = ['atestado_lastro','Exigência de comprovação da capacidade técnico-operacional das licitantes para serviços comuns em obras.']
recomposicao = ['recomposicao','Exigência de comprovação da capacidade técnico-operacional das licitantes para serviços comuns em obras.']
atestado_regularizacao = ['atestado_regularizacao','Exigência de comprovação da capacidade técnico-operacional das licitantes para serviços comuns em obras.']
atestado_remendo = ['atestado_remendo','Exigência de comprovação da capacidade técnico-operacional das licitantes para serviços comuns em obras.']
atestado_escavacao = ['atestado_escavacao','Exigência de comprovação da capacidade técnico-operacional das licitantes para serviços comuns em obras.']
atestado_carga = ['atestado_carga','Exigência de comprovação da capacidade técnico-operacional das licitantes para serviços comuns em obras.']
atestado_corte = ['atestado_corte','Exigência de comprovação da capacidade técnico-operacional das licitantes para serviços comuns em obras.']
atestado_terraplanagem = ['atestado_terraplanagem','Exigência de comprovação da capacidade técnico-operacional das licitantes para serviços comuns em obras.']
atestado_sondagem_manual = ['atestado_sondagem_manual','Exigência de comprovação da capacidade técnico-operacional das licitantes para serviços comuns em obras.']
atestado_sondagem = ['atestado_sondagem','Exigência de comprovação da capacidade técnico-operacional das licitantes para serviços comuns em obras.']
atestado_transporte = ['atestado_transporte','Exigência de comprovação da capacidade técnico-operacional das licitantes para serviços comuns em obras.']
atestado_apicoamento = ['atestado_apicoamento','Exigência de comprovação da capacidade técnico-operacional das licitantes para serviços comuns em obras.']
atestado_remocao = ['atestado_remocao','Exigência de comprovação da capacidade técnico-operacional das licitantes para serviços comuns em obras.']
atestado_argamassa = ['atestado_argamassa','Exigência de comprovação da capacidade técnico-operacional das licitantes para serviços comuns em obras.']
atestado_concreto = ['atestado_concreto','Exigência de comprovação da capacidade técnico-operacional das licitantes para serviços comuns em obras.']
atestado_base_ou_leito = ['atestado_base_ou_leito','Exigência de comprovação da capacidade técnico-operacional das licitantes para serviços comuns em obras.']
atestado_desobstrucao = ['atestado_desobstrucao','Exigência de comprovação da capacidade técnico-operacional das licitantes para serviços comuns em obras.']
atestado_limpeza = ['atestado_limpeza','Exigência de comprovação da capacidade técnico-operacional das licitantes para serviços comuns em obras.']
carregadeira_pneus = ['carregadeira_pneus','O uso de carregadeira de pneus com capacidade de 1,53, 1,72, 2,9, 3,3 m³ é antieconômico frente ao uso de escavadeira hidráulica em obras de médio / grande porte.']
rocha3a = ['rocha3a','A escavação em rocha dura ou de 3ª categoria é um serviço no qual é recomendado uma maior atenção e avaliação econômica, caso seja item materialmente relevante da curva ABC.']
trator_esteiras = ['trator_esteiras','O uso do trator de esteiras com lâmina com potência de 74,5 kW ou 112 kW é antieconômico frente ao uso de trator de esteiras com lâmina com potência de 259 kW em obras de médio/grande porte.']
trator_esteiras_laminas = ['trator_esteiras_laminas','O uso do trator de esteiras com lâmina com potência de 74,5 kW ou 112 kW é antieconômico frente ao uso de trator de esteiras com lâmina com potência de 259 kW em obras de médio/grande porte.']
areia_comercial = ['areia_comercial','O uso de areia comercial é antieconômico frente ao uso de areia extraida de jazida']
brita_comercial = ['brita_comercial','O uso de brita comercial ou pedra britada é antieconômico frente ao uso desses mesmos insumos produzidos na jazida']
compactador_manual = ['compactador_manual','O uso de compactador manual em compactação, aterro ou reaterro é antieconômico frente ao uso de equipamentos de compactação de maior porte em obras de médio/grande porte.']
transporte_manual = ['transporte_manual','O uso de transporte manual é antieconômico frente ao uso de equipamentos no transporte em obras de médio/grande porte.']
roçagem_poda_corte_manual = ['roçagem_poda_corte_manual','O uso de roçagem, capina, poda ou corte manual é antieconômico frente ao uso de equipamento mecânico para as mesmas atividades em obras de médio/grande porte.']
alvenaria_deitada = ['alvenaria_deitada','O tijolo deitado, bloco deitado, alvenaria deitada ou de uma vez é antieconômico frente ao uso de alvenaria convencional quando esta solução não é tecnicamente necessária ou foi realizada parede de alvenaria convencional.']

certificado_registro_cadastral = ['certificado_registro_cadastral','Exigência de Certificado de Registro Cadastral (CRC)']
doc_firma_reconhecida_cartorio = ['doc_firma_reconhecida_cartorio','Exigência de documentação com firma reconhecida em cartório']
certificado_boas_praticas = ['certificado_boas_praticas','Exigência de Certificados de boas práticas']
exigencia_posse_previa = ['exigencia_posse_previa','Exigência para habilitação a posse, propriedade ou localização prévia de veículos, máquinas ou equipamentos a serem utilizados na execução do objeto licitado']
licenca_ambiental = ['licenca_ambiental','Exigência de licença ambiental para habilitação no certame']
vinculo_empregaticio = ['vinculo_empregaticio','Exigência de vínculo empregatício de profissionais de nível superior (CTPS) para comprovar qualificação técnica']
cadastro_previo = ['cadastro_previo','Exigência de cadastro prévio irregular (prazo indevido na TP, obrigatório nas outras)']
certificado_qualidade = ['certificado_qualidade','Exigência de certificado de qualidade não obrigatório por lei (ABIC, ABNT, ISO, etc)']
comprovacao_atividade = ['comprovacao_atividade','Exigência de comprovação de atividade ou de aptidão com limitações de tempo ou de época ou ainda em locais específicos, ou quaisquer outras não previstas na legislação, que inibam a participação na licitação.']
vedacao_documento = ['vedacao_documento','Veda-se apresentação de documentos via postal, fax ou e-mail']

lista_geral = [alimentos_caros,bebidas_alcoolicas,comida_japonesa, itens_caros, garantia_cs_ou_pl,
                       vedacao_impugnacao,preferencia_prod_nacionais,atestado_compactador,atestado_aterro,atestado_demolicao,atestado_lastro,recomposicao,atestado_regularizacao,atestado_remendo,atestado_escavacao,atestado_carga,atestado_corte,
                       atestado_terraplanagem,atestado_sondagem_manual,atestado_sondagem,atestado_transporte,atestado_apicoamento,atestado_remocao,atestado_argamassa,atestado_concreto,atestado_base_ou_leito,atestado_desobstrucao,atestado_limpeza,carregadeira_pneus,rocha3a,
                       trator_esteiras,trator_esteiras_laminas,areia_comercial,brita_comercial,compactador_manual,transporte_manual,roçagem_poda_corte_manual,alvenaria_deitada]

lista_habilitacao = [certidao_protesto, certidao_corregedor, integralizado, idoneidade_financeira, 
certidao_quitacao, carta_credenciamento, filiacao_abav_iata, visto_registro_profissional, 
comprovante_localizacao, usina_asfalto_cbuq, amostra_prototipo, n_min_max_limitacao_atestados,
 temp_exp_profissional, quadro_permanente, certificado_registro_cadastral, doc_firma_reconhecida_cartorio, certificado_boas_praticas,
exigencia_posse_previa, licenca_ambiental, vinculo_empregaticio, cadastro_previo, certificado_qualidade,
comprovacao_atividade, vedacao_documento]